[build-system]
requires = [
   "setuptools",
   "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "tensorgrad"
version = "0.1"
dependencies = [
   "networkx",
   "torch",
   "nbval",
   "pytest",
   "pdf2image"
]

[tool.setuptools]
packages = ["tensorgrad"]

[tool.ruff]
line-length = 110
indent-width = 4

[tool.pytest.ini_options]
addopts = "--nbval"
